export * from './assign-instruction.js'
export * from './call-instruction.js'
export * from './exec-instruction.js'
export * from './instruction.js'
export * from './load-instruction.js'
export * from './lock-instruction.js'
export * from './new-instruction.js'
