name: Run tests for js packages
run-name: Js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 19.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Cache yarn
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: yarn-deps-${{ runner.os }}-${{ hashFiles('./yarn.lock')}}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: (cd docs && yarn install)
      - run: yarn build
      - run: yarn ci
      - name: Save yarn
        id: cache-yarn-save
        uses: actions/cache/save@v3
        with:
          path: |
            ./node_modules
          key: ${{ steps.cache-yarn.outputs.cache-primary-key }}
